import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
//components

import Navbar from '../../components/navbar/navbar'
import Button from '../../components/Button/'
import Skills from '../../components/skills'
import Footer from '../../components/footer/'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.MainHeader}>
        <Navbar/>
      </header>
      <main className={styles.main}>
          {/* Home */}
          <div className={styles.BannerHome}>
            <div className={styles.BannerHomeContainer}>
                <h1>Hi, i´m Victor&nbsp;Basso</h1>
                <p>Desenvolvedor de software <span>Fullstack</span>_</p>
                <div className={styles.ButtonsHere}>
                  <Link href="/Contact"> 
                    <Button text="Hire me" color="var(--Second-Color)"/>
                  </Link>
                  <Link href="/Profile" className={styles.SimpleButton}>
                    <p>About me</p>
                  </Link>
                </div>
               
                <Image className={styles.Sticker}  alt="Victor Basso Programador" src="/sticker.png" width={280} height={280}>

                </Image>
            </div>  
          </div>
          {/* skills */}
          <Skills/>
      </main>
      <Footer/>

    </>
  )
}
